# Generated by Django 6.0.1 on 2026-01-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_available_weights_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifestyle_image',
            field=models.ImageField(blank=True, null=True, upload_to='lifestyle/'),
        ),
    ]
