# Generated by Django 6.0.1 on 2026-01-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, help_text='e.g. Contains Milk', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN/Barcode', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_info',
            field=models.CharField(blank=True, help_text='e.g. Printed on package', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='nutritional_info',
            field=models.JSONField(blank=True, help_text='Nutrient amounts per 100ml/g', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, help_text='e.g. Carton', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_method',
            field=models.CharField(blank=True, help_text='e.g. Pasteurized', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='e.g. Perishable beverage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_certification',
            field=models.CharField(default='KEBS certified', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_cold_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='same_day_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Product ID (SKU)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
