# Generated by Django 6.0.1 on 2026-01-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_allergens_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='purpose',
            field=models.CharField(choices=[('main', 'Main Image (Gallery)'), ('packaging', 'Packaging (Close-up)'), ('nutrition', 'Nutrition Label'), ('usage', 'Usage (Real-life context)'), ('storage', 'Storage handling guide')], default='main', help_text='Specifies where this image will appear in the frontend detail explanations.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed explanation of origin, processing, and use.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order',
            field=models.PositiveIntegerField(default=12, help_text='Value in units (Logic will convert to Dozens in Frontend)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.JSONField(blank=True, help_text="Nutrient amounts per 100ml/g (e.g. {'Protein': '3.3g', 'Fat': '3.6g'})", null=True),
        ),
    ]
