# Generated by Django 6.0.1 on 2026-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage_purpose_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text="Nutrient amounts per 100ml/g (e.g. {'Protein': '3.3g', 'Fat': '3.6g'})", null=True),
        ),
    ]
