# Generated by Django 6.0.1 on 2026-01-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_nutritional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='purpose',
        ),
        migrations.AddField(
            model_name='product',
            name='nutrition_image',
            field=models.ImageField(blank=True, help_text='Verified facts & certifications image.', null=True, upload_to='products/technical/'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_image',
            field=models.ImageField(blank=True, help_text='Visual brand & size verification image.', null=True, upload_to='products/technical/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Enter nutrition facts as plain text.', null=True),
        ),
    ]
