# Generated by Django 6.0.1 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='limit',
            field=models.PositiveIntegerField(default=1, help_text='Total usage limit for this voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
